apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels:
    app: web
    env: dev
  annotations:
    description: "This is development stage"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
